### ISSUE TITLE
[BUG] Swapper UI mouse sensitivity very high

### ISSUE THREAD

**Issue by Treetrain1** [tr7zw/ItemSwapper#185] opened 2023-11-10 01:47 UTC
### Version information

itemswapper-fabric-0.5.3-mc1.20.1

### Expected Behavior

I would expect it to respect the setting like any other GUI

### Actual Behavior

It just acts as if the vanilla Raw Input option is off

### Reproduction Steps

1: turn on raw input
2: observe

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by tr7zw** [comment] 2023-11-10 01:48
I have no clue what you mean with raw input tbh?

**Comment by tr7zw** [comment] 2023-11-10 01:50
If you mean the mouse movement, it's getting the mouse changes that the ingame camera would use, since its not technically a normal GUI. That should use the raw mouse movements. as its using the same values.

**Comment by Treetrain1** [comment] 2023-11-10 01:54
> If you mean the mouse movement, it's getting the mouse changes that the ingame camera would use, since its not technically a normal GUI. That should use the raw mouse movements. as its using the same values.

actually it might be sensitivity instead
for whatever reason, the mouse speed is significantly higher in the gui

**Comment by tr7zw** [comment] 2023-11-10 01:55
Its not the windows cursor, so yes, the mouse speed won't be the same. Just go into the mod setting and change it to your liking.

**Comment by Treetrain1** [comment] 2023-11-10 01:55
> Its not the windows cursor, so yes, the mouse speed won't be the same. Just go into the mod setting and change it to your liking.

hmm
why is it different?

**Comment by tr7zw** [comment] 2023-11-10 01:58
Because its not the real mouse. The game still captures the mouse so you can move with wasd or sneak, also to keep the fake cursor in the relevant part of the screen, so you cant accidentally flip it outside of the window or anything. You probably have your mouse really fast, but then mc set to really low sensitivity or something like that. For most people, the default setting will feel fine, but unusual mouse settings will require calibrating it in the settings.

**Comment by Treetrain1** [comment] 2023-11-10 02:00
> Because its not the real mouse. The game still captures the mouse so you can move with wasd or sneak, also to keep the fake cursor in the relevant part of the screen, so you cant accidentally flip it outside of the window or anything. You probably have your mouse really fast, but then mc set to really low sensitivity or something like that. For most people, the default setting will feel fine, but unusual mouse settings will require calibrating it in the settings.

yes i have a high dpi mouse
i have the sensitivity very low in the game but its very fast in the item swapper gui still
so i wonder what differences different dpi settings have on the gui

**Comment by tr7zw** [comment] 2023-11-10 02:01
The issue is that its taking the raw mouse input before the vanilla mc mouse settings get applied, since that has its own slide.

**Comment by Treetrain1** [comment] 2023-11-10 02:04
> The issue is that its taking the raw mouse input before the vanilla mc mouse settings get applied, since that has its own slide. As I said, go into the mod settings, and turn the sensitivity down.

do you think it would be possible to have an option to sync with minecraft sensitivity?
as a modpack creator, it would be annoying for players to each have to change the sensitivity manually. that's my main concern

**Comment by tr7zw** [comment] 2023-11-10 02:12
No. These are 2 unrelated values(they were the same initially, but got requested from people with weird mouse settings to split that off, as it makes no sense to have them the same). As I said, for 95+% of ppl the default value is fine. Since #16 from last year there hasn't been anyone having issues with it, and the point of that already was to "Adjusted mouse sensitivity to more closely match other GUIs.". So I don't think there is anything that needs to be done, since in the very worst case it can be fixed by changing the setting, exactly how you need to change the vanilla settings with too high mouse settings as you use(you need to do that for any modpack too).

**Comment by tr7zw** [comment] 2024-02-18 21:44
Closing this, as the main conflict/issue has been resolved(if you use stupid high dpi, set the speed in the options to what feels right).

**Closed by tr7zw** 2024-02-18 21:44 UTC
Labels: bug
