### ISSUE TITLE
Close UI with Esc key, when togglemode is active

### ISSUE THREAD

**Issue by AdvancedWipe** [tr7zw/ItemSwapper#59] opened 2022-12-04 20:29 UTC
I am missing the ability to close the GUI with the Esc key instead of pressing the R key again to close it.

**Comment by tr7zw** [comment] 2022-12-04 20:30
Duplicate of #31.

**Closed by tr7zw** 2022-12-04 20:30 UTC

**Comment by AdvancedWipe** [comment] 2022-12-04 20:31
Oops, completely missed that one.
