### ISSUE TITLE
[Suggestion] adding compatibility with midnight controls

### ISSUE THREAD

**Issue by KairuDeibisu** [tr7zw/ItemSwapper#52] opened 2022-12-04 16:37 UTC
I program software system professional and spend so much time typing that I get a lot of pain in my hands.

I'm unable to use a keyboard to play video games. 

The only way I can play Minecraft is with a controller mod.

I would love to be able to use the item swapper with that mod in conjunction. 

Additionally, assuming Mojang wants to use the item swapper, in the future. It would need to somehow be mapped to a controller. It'd be cool to start thinking about how that could be done.

**Comment by tr7zw** [comment] 2022-12-04 16:44
I think this might be a duplicate of #24 ? There it was primarily about the Steam Deck, but I guess it applies to the controller mod in general.

**Comment by KairuDeibisu** [comment] 2022-12-04 16:54
> I think this might be a duplicate of #24 ? There it was primarily about the Steam Deck, but I guess it applies to the controller mod in general

I wasn't even thinking about the steam deck.

I do play on the steam deck as well, and the controllable mod, allows controllers of any kind to work.

I believe the main issue is compatibility with the controllable mod and not the steam deck.

**Comment by tr7zw** [comment] 2022-12-04 16:56
Ah, so Controllable is a different mod, I assumed the question was also about the MidnightControlls mod, which also adds controller support.

**Comment by tr7zw** [comment] 2022-12-04 16:57
Ah, then I'll close this as a duplicate and clarify on the other ticket, that it's about MidnightControlls, not exclusively the Steam Deck.

**Closed by tr7zw** 2022-12-04 16:57 UTC

**Comment by KairuDeibisu** [comment] 2022-12-04 17:00
After looking into it more, I misremember the name of the mod. The mod is midnight controls. Midnight controls is for fabric.

Compatibility isn't about a code issue. The code doesn't seem to conflict.

The issue is how buttons are being bound. It makes it hard or impossible to bind item swap buttons to the controller using the mod.

I'm going to test it out and post a full breakdown what's going on.
