### ISSUE TITLE
[Suggestion] Make Shulker Box Pulling be Optional

### ISSUE THREAD

**Issue by AidanR8459** [tr7zw/ItemSwapper#107] opened 2022-12-28 01:53 UTC
Hi @tr7zw and @Xisuma 

I was wondering if you could make it so that Item Swapper pulling from Shulker boxes be optional, as I think that some in the community might like that kind of control over what is happening in the mod. Say you have a Shulker Box full of stuff for your friend on a Multiplayer server, and you need an item on the way there, but you accidentally pull it from the Shulker Box and so your friend gets mad at you for not delivering as agreed? Of course, this is just an example of what could happen and what could be done to stop this kind of thing.

Kind Regards,
[AidanPlayz8459](https://linktr.ee/aidanplayz)

**Comment by tr7zw** [comment] 2022-12-28 01:55
Shulkers only works in Multiplayer, if the server has the mod/plugin. So unless everyone has the option to use the Shulker, no one has(items from shulkers also will not be shown as an option).
Duplicate of #54

**Closed by tr7zw** 2022-12-28 01:55 UTC

**Comment by tr7zw** [comment] 2022-12-28 02:19
![grafik](https://user-images.githubusercontent.com/5133936/209746990-98490f3a-600e-45cf-ba0b-1c1c22378a67.png)
closes as duplicate. Github: "not planned" 🤔
