### ISSUE TITLE
Cant use itemswapper menu with candle-colourvariations

### ISSUE THREAD

**Issue by A1ver** [tr7zw/ItemSwapper#35] opened 2022-12-03 18:30 UTC
(i tried this in creative) you can swap from light sources to a candle, and from a candle to candle colour variations, but once you have a coloured candle in your hotbar you cant use the menu on the candle.

**Comment by tr7zw** [comment] 2022-12-20 19:06
Going to mark this one as a duplicate of #80 , because that issue identified the cause.

**Closed by tr7zw** 2022-12-20 19:06 UTC
