### ISSUE TITLE
Intergation with Inventory Profile Next

### ISSUE THREAD

**Issue by yarndinasti** [tr7zw/ItemSwapper#99] opened 2022-12-19 07:01 UTC
I can't pick item when using **Inventory Profile Next** and `locked_slots_empty_hotbar_as_semi_locked` **true**

Say IPN dev, no have integration between 2 mods

https://github.com/blackd/Inventory-Profiles/issues/254

**Comment by tr7zw** [comment] 2022-12-19 19:10
I had written with him, the issue is that it's way out of the scope of the current mod, to try to get full mod support with other mods. Added to that, getting items from shulkers can't be supported with the way IPN currently works(it can only handle inventory actions).
I can provide API that announces to other mods when an item swap will happen, but due to the incompatible interface(he linked https://github.com/blackd/Inventory-Profiles/blob/all-in-one/shared-sources/src/main/kotlin/org/anti_ad/mc/ipn/api/access/IContainerClicker.kt ), I can't add the full support from my end.

**Comment by tr7zw** [comment] 2022-12-19 19:55
```java
        ItemSwapperClientAPI.getInstance().itemSwapEvent.register(onSwap -> {
            System.out.println("Swap! " + onSwap.slot());
            onSwap.canceled().set(true);
        });
```
Ok I've added a really basic event system and event that gets fired, right before the swap. The even can be canceled too, so IPN could use its on method to do the swap. This will won't fix the shulker issue(since that happens on the server side).

**Closed** 2022-12-19 20:56 UTC
