### ISSUE TITLE
[Suggestion] Though clicking E would open inventory, holding it down would open Palette

### ISSUE THREAD

**Issue by Boden-C** [tr7zw/ItemSwapper#211] opened 2024-05-21 03:43 UTC
### Is your feature request related to a problem?

As seen by #154 and general "too many keybinds in modpacks" (I already have my close keybinds bound to other things), my next closest keybind is too far away for me to use it meaningfully

### Describe the solution you'd like

A solution would be to use inventory key E but make it so that if you press it (maybe keyDown and keyUp within a few milliseconds) it will open regular inventory, but if you hold it (maybe keyDown for more than the few milliseconds) it will open Pallete instead while it is held.

You could also simulate Alt+Tab behavior where the Palette would immediately open on keyDown but if a keyUp happens within a few milliseconds than the inventory would open. This could cause a flash of the Palette though.

I feel like this is the most beginner-friendly functionality possible as we are already used to using E, item swapper would basically be a "quick inventory function" where you hold your inventory key, choose the option, and then let go instead of being a separate key.

**Comment by tr7zw** [comment] 2024-05-25 19:26
This is a duplicate of #154 , which suggested the exact same thing^^

**Closed by tr7zw** 2024-05-25 19:26 UTC
Labels: enhancement
