### ISSUE TITLE
Text overlapping on block palette

### ISSUE THREAD

**Issue by YandeMC** [tr7zw/ItemSwapper#110] opened 2022-12-28 21:34 UTC
![image](https://user-images.githubusercontent.com/113806118/209874472-8798dbba-f39d-48cc-bf0e-04a5512cbfb7.png)

**Comment by tr7zw** [comment] 2022-12-28 21:35
Duplicate of #103 , but with getting a screen I can tell you the issue: #33 . For now the solution is to not use Optifine.

**Closed by tr7zw** 2022-12-28 21:35 UTC
